version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0 # HACK: Disable automatic PRs.
    allow:
      - dependency-name: "*"
        dependency-type: "production"