name: Publish Docs

on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit Message'
        default: 'docs: Publish documentation website'
        required: false

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:
    name: Publish Docs
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GIT_TOKEN }}

      - name: Setup
        run: make setup

      - name: Publish Docs
        run: |
          make website
          make publish-website

